sudo: false

language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.2
    - php: 7.0
  fast_finish: true

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
